version: '3.8'

services:
  frontend:
    # IMAGEM DO GHCR (GitHub Container Registry)
    image: ghcr.io/flaviosantti/bom-pastor-frontend:latest

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=Favucanet"
        - "traefik.http.routers.bompastor-frontend.rule=Host(`bompastordigital.flaviosantiago.com.br`)"
        - "traefik.http.routers.bompastor-frontend.entrypoints=websecure"
        - "traefik.http.routers.bompastor-frontend.tls.certresolver=myresolver"
        - "traefik.http.routers.bompastor-frontend.service=bompastor-frontend-svc"
        - "traefik.http.services.bompastor-frontend-svc.loadbalancer.server.port=80"
        - "traefik.http.middlewares.bompastor-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.bompastor-http.rule=Host(`bompastordigital.flaviosantiago.com.br`)"
        - "traefik.http.routers.bompastor-http.entrypoints=web"
        - "traefik.http.routers.bompastor-http.middlewares=bompastor-https-redirect"

    # Conecta à rede externa do Traefik
    networks:
      - Favucanet

# Define a rede externa onde o Traefik está rodando
networks:
  Favucanet:
    external: true
